# Generated by Django 6.0 on 2026-01-03 06:39

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Shipment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('package_id', models.IntegerField()),
                ('courier_name', models.CharField(max_length=100)),
                ('tracking_number', models.CharField(max_length=100, unique=True)),
                ('status', models.CharField(default='IN_TRANSIT', max_length=50)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
